<?php

function tb_messages_views_pre_build(&$view) {

}

function tb_messages_preprocess_views_view_field(&$vars) {
  if($vars['view']->current_display == ''){
    
  }
}

/*
 * Returns quantity of new messages in all dialogs in which current user takes a part.
 */
function tb_messages_get_new_messages_quantity(){
    global $user;
    $comments = db_query("
        SELECT COUNT(DISTINCT B.cid) FROM field_data_field_users A JOIN comment B ON A.entity_id = B.nid
           JOIN history C ON B.nid = C.nid WHERE C.timestamp < B.changed AND field_users_target_id = :user AND C.uid = :user
    ", array(":user" => $user->uid));
    foreach($comments as $comment){
        foreach($comment as $key => $val){
            if($val != 0){
                return "($val)";
            }else{
                return "";
            }
        }
    }

    return "";
}

/*
 * Posting comment without being redirected.
 */
/*
function tb_messages_comment_submit($form, &$form_state){
    comment_form_submit($form, $form_state);

    $comment = comment_load($form_state['values']['cid']);
    $node = node_load($form_state['values']['nid']);
    $commands = array(
        ajax_command_prepend('#comments-dialog', render(comment_view($comment, $node, "full", LANGUAGE_NONE))),
    );
    $replace = array('#type' => 'ajax', '#commands' => $commands);
    return $replace;
}
*/