<?php

/**
 * Implements hook_menu().
 */
function tb_settings_menu() {
  $items = array();
  
  $items['admin/tb-settings'] = array(
    'title' => 'TicketBaby settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tb_settings_admin_form'),
    'access arguments' => array("administer site configuration"),
  );

  return $items;
}

function tb_settings_admin_form($form, &$form_state){
  $form['default_ticket_category_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Default ticket category id'),
    '#default_value' => variable_get("default_ticket_category_id", 12),
    '#size' => 10,
    '#maxlength' => 10,
    '#description' => t('When user create ticket he should see default ticket if no variable pass.'),
    '#required' => TRUE,
  );
  
  $form['default_ticket_fields'] = array(
    '#type' => 'textarea',
    '#title' => t("Default ticket fields"),
    '#default_value' => variable_get("default_ticket_fields", "field_ticket_category\nfield_date_of_ticket"),
    '#description' => t("PLEASE DON'T CHANGE IF YOU ARE NOT SURE! Default ticket fields in creation form - doesn't matter which category user select. Use new line to separate."),
    '#required' => TRUE,
  );
  return system_settings_form($form);
}

/*
 * Implements hook_init().
 */
function tb_settings_init(){
    global $user;
    // Check if we are on user/tickets page.
    // Check if this user is customer.
    // If we have only one ticket available go to ticket page.
    if(arg(0). '/'. arg(1) == 'user/my-tickets'){
        if(in_array('customer', $user->roles)){
            $ticket = tb_user_menu_have_one_ticket();
            if($ticket['only_one']){
                drupal_goto("node/". $ticket['nid']);
            }
        }
    }
}