  <?php

/**
 * Implements hook_menu().
 */

function tb_user_menu_menu(){
  $items = array();

  $items['my-tickets'] = array(
    'title' => t('My tickets'),
    'description' => t('My tickets.'),
    'page callback' => 'tb_user_menu_my_tickets',
    'page arguments' => array(),
    'access arguments' => array('access content'),
  );
  
  return $items;
}

/*
 * Callback
 */

function tb_user_menu_my_tickets(){
  global $user;
  drupal_goto('user/'. $user->uid. '/tickets');
}

function tb_user_menu_init(){
  drupal_add_js(drupal_get_path('module', 'tb_user_menu'). '/js/header-menu.js');
  drupal_add_css(drupal_get_path('module', 'tb_user_menu'). '/css/header-menu.css');
}