<?php
/* Add custom view modes */
/**
 * Implements hook_entity_info_alter().
 * The first attribute in the array defines an arbitrary label for the view mode machine name.
 * 'custom settings' => TRUE displays the view mode as a default at the top of the display modes settings screen
 */

function tb_user_entity_info_alter(&$entity_info){
    $entity_info['user']['view modes'] += array(
        'dialogs' => array(
            'label' => t('Image on dialogs list'),
            'custom settings' => TRUE,
        ),
    );
}

/*
 * Implements hook_form_alter();
 */
function tb_user_form_alter(&$form, &$form_state, $form_id){
    global $user;
    if($form_id == "user_profile_form" && in_array("customer", $user->roles)){
        // Customer shouldn't have a picture.
        if(isset($form['picture'])) unset($form['picture']);
    }

}