<?php

/*function tb_user_dialog_views_pre_build(&$vars) {

}*/

function tb_user_dialog_preprocess_comment(&$variables){
    $author = user_load($variables['comment']->uid);
    if(isset($author->field_fullname[LANGUAGE_NONE][0]['value'])){
        $author = $author->field_fullname[LANGUAGE_NONE][0]['value'];
        $variables['author'] = $author;
    }
}

/*
* After build - remove text format description from fields.
*/
function tb_user_dialog_remove_format_description($form){
  $form['comment_body'][LANGUAGE_NONE][0]['format']['#access'] = false;
  return $form;
}

/*
 * Creating new dialog form.
 */
function tb_user_dialog_form_alter(&$form, &$form_state, $form_id){
    if($form_id == "comment_node_dialog_form"){
        unset($form['author']['_author']);
        $form['comment_body'][LANGUAGE_NONE][0]['#title_display'] = 'invisible';
        $form['#after_build'][] = 'tb_user_dialog_remove_format_description';
    }
    if($form_id == "dialog_node_form" && !user_access("administer content types")){
        global $user;
        // Get variables from url.
        $type = arg(0) == 'user' ? 'user' : '';
        // ticket node/nid or ticket/nid/defender page.
        $type = arg(0) == 'node' || (arg(0) == 'ticket' && intval(arg(1)) && arg(2) == 'defender') ? 'ticket' : $type;
        $id = arg(1);

        if($type === null || $id === null || !intval($id)){
            //drupal_not_found();
        }

        // We will check if any $type detected and return page not found if not.
        $processed = false;
        if($type == "ticket"){
            $ticket = node_load($id);
            if(!$ticket){
                drupal_not_found();
            }elseif($ticket->type != $type){
                drupal_not_found();
            }else{
                // Add js to slideDown textfield.
                $form['#attached']['js'][] = drupal_get_path('module', 'tb_user_dialog'). '/js/contact.js';
                // Set attached_to field and users field.
                $form['field_attached_to'][LANGUAGE_NONE][0]['target_id']['#value'] = $ticket->title. ' ('. $ticket->nid. ')';
                $author = user_load($ticket->uid);
                $form['field_users'][LANGUAGE_NONE][0]['target_id']['#value'] = $user->name. ' ('. $user->uid. ')';
                // Copy all info from already prepared field...
                $form['field_users'][LANGUAGE_NONE][1] = $form['field_users'][LANGUAGE_NONE][0];
                // Then just change uid and name.
                $form['field_users'][LANGUAGE_NONE][1]['target_id']['#value'] = $author->name. ' ('. $author->uid. ')';
                $processed = true;
            }
        }
        if($type == "user"){
            $user_to = user_load($id);
            if(!$user_to){
                drupal_not_found();
            }else{
                // Add js to slideDown textfield.
                $form['#attached']['js'][] = drupal_get_path('module', 'tb_user_dialog'). '/js/contact.js';
                // Set users field.
                $form['field_users'][LANGUAGE_NONE][0]['target_id']['#value'] = $user_to->name. ' ('. $user_to->uid. ')';
                // Copy all info from already prepared field...
                $form['field_users'][LANGUAGE_NONE][1] = $form['field_users'][LANGUAGE_NONE][0];
                // Then just change uid and name.
                $form['field_users'][LANGUAGE_NONE][1]['target_id']['#value'] = $user->name. ' ('. $user->uid. ')';
                $processed = true;
            }
        }

        if(!$processed){
            //drupal_not_found();
        }
        // Prepare form.

        $form['body'][LANGUAGE_NONE][0]['value']['#title_display'] = 'invisible';
        $description = $form['body'][LANGUAGE_NONE][0]['value']['#description'];
        $form['body'][LANGUAGE_NONE][0]['value']['#description'] = '';
        $form['body'][LANGUAGE_NONE][0]['value']['#attributes']['placeholder'] = array($description);
        $form['field_attached_to']['#access'] = false;
        $form['field_users']['#access'] = false;
        $form['actions']['submit']['#value'] = "Send";

    }
}

/*
 * Implements hook_node_access().
 */
function tb_user_dialog_node_access($node, $op, $account){
  $type = is_string($node) ? $node : $node->type;
  if($type == 'dialog'){
    if($op == 'view'){
      // Let ticket's owner to see this offer.
      global $user;
      foreach($node->field_users[LANGUAGE_NONE] as $key => $value){
        if($value['target_id'] == $user->uid){
          return NODE_ACCESS_ALLOW;
        }
      }
      return NODE_ACCESS_DENY;
    }
  }
  return NODE_ACCESS_IGNORE;
}